Sublime-Backend-Assessment/Models/SverigesRadio/BaseModels/Channel.cs
namespace Sublime_Backend_Assessment.Models.BaseModels.SverigesRadio
{
    public class Channel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Sublime-Backend-Assessment/Models/SverigesRadio/BaseModels/Pagination.cs
namespace Sublime_Backend_Assessment.Models.BaseModels.SverigesRadio
{
    public class Pagination
    {
        public int Page { get; set; }
        public int Size { get; set; }
        public int TotalHits { get; set; }
        public int Totalpages { get; set; }
        public string Nextpage { get; set; }
    }
}

Sublime-Backend-Assessment/Models/SverigesRadio/BaseModels/Podcast.cs
using Sublime_Backend_Assessment.Models.BaseModels.SverigesRadio;
using Sublime_Backend_Assessment.Utility;

namespace Sublime_Backend_Assessment.Models.SverigesRadio.BaseModels
{
    public class Podcast
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long Filesizeinbytes { get; set; }
        public Channel Program { get; set; }
        public string Availablefromutc { get; set; }

        private string _duration;
        public string Duration
        {
            get => _duration.DurationFormater();
            set { _duration = value; }
        }

        private string _publishdateutc;
        public string Publishdateutc
        {
            get => _publishdateutc.DateParser().DateFormater();
            set { _publishdateutc = value; }
        }
        public string Url { get; set; }
        public string Statkey { get; set; }
    }
}

Sublime-Backend-Assessment/Models/SverigesRadio/BaseModels/Program.cs
using Sublime_Backend_Assessment.Models.BaseModels.SverigesRadio;
using System.Collections.Generic;

namespace Sublime_Backend_Assessment.Models.SverigesRadio.BaseModels
{
    public class Program
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ProgramCategory Programcategory { get; set; }
        public string Broadcastinfo { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Programurl { get; set; }
        public string Programslug { get; set; }
        public string Programimage { get; set; }
        public string Programimagetemplate { get; set; }
        public string Programimagewide { get; set; }
        public string Programimagetemplatewide { get; set; }
        public string Socialimage { get; set; }
        public string Socialimagetemplate { get; set; }
        public List<Socialmediaplatform> Socialmediaplatforms { get; set; }
        public Channel Channel { get; set; }
        public bool Archived { get; set; }
        public bool Hasondemand { get; set; }
        public bool Haspod { get; set; }
        public string Responsibleeditor { get; set; }
        public List<Podcast> Podcasts { get; set; }

    }
}

Sublime-Backend-Assessment/Models/SverigesRadio/BaseModels/ProgramCategory.cs
namespace Sublime_Backend_Assessment.Models.BaseModels.SverigesRadio
{
    public class ProgramCategory
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Sublime-Backend-Assessment/Models/SverigesRadio/BaseModels/ResponseWrapper.cs
namespace Sublime_Backend_Assessment.Models.BaseModels.SverigesRadio
{
    public class ResponseWrapper
    {
        public string Copyright { get; set; }
        public Pagination Pagination { get; set; }     
    }
}

Sublime-Backend-Assessment/Models/SverigesRadio/BaseModels/Socialmediaplatform.cs
namespace Sublime_Backend_Assessment.Models.SverigesRadio.BaseModels
{
    public class Socialmediaplatform
    {
        public string Platform { get; set; }
        public string Platformurl { get; set; }
    }
}

Sublime-Backend-Assessment/Models/SverigesRadio/PodcastsWrapper.cs
using Sublime_Backend_Assessment.Models.BaseModels.SverigesRadio;
using Sublime_Backend_Assessment.Models.SverigesRadio.BaseModels;
using System.Collections.Generic;

namespace Sublime_Backend_Assessment.Models.SverigesRadio
{
    public class PodcastsWrapper: ResponseWrapper
    {
        public List<Podcast> Podfiles { get; set; }
    }
}

Sublime-Backend-Assessment/Models/SverigesRadio/ProgramCategoryWrapper.cs
using Sublime_Backend_Assessment.Models.BaseModels.SverigesRadio;
using System.Collections.Generic;

namespace Sublime_Backend_Assessment.Models.SverigesRadio
{
    public class ProgramCategoryWrapper : ResponseWrapper
    {
        public List<ProgramCategory> Programcategories { get; set; }
    }
}

Sublime-Backend-Assessment/Models/SverigesRadio/ProgramGroupedPresenter.cs
using Sublime_Backend_Assessment.Models.SverigesRadio.BaseModels;
using System.Collections.Generic;

namespace Sublime_Backend_Assessment.Models.SverigesRadio
{
    public class ProgramGroupedPresenter
    {
        public string Name { get; set; }
        public List<Program> Programs { get; set; }
    }
}

Sublime-Backend-Assessment/Models/SverigesRadio/ProgramsWrapper.cs
using Sublime_Backend_Assessment.Models.BaseModels.SverigesRadio;
using Sublime_Backend_Assessment.Models.SverigesRadio.BaseModels;
using System.Collections.Generic;

namespace Sublime_Backend_Assessment.Models.SverigesRadio
{
    public class ProgramsWrapper: ResponseWrapper
    {
        public List<Program> Programs { get; set; }
    }
}

Sublime-Backend-Assessment/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Sublime_Backend_Assessment.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Sublime-Backend-Assessment/Controllers/SverigesRadioController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using Sublime_Backend_Assessment.Models.SverigesRadio;
using Sublime_Backend_Assessment.Repository;
using Sublime_Backend_Assessment.Utility;
using Sublime_Backend_Assessment.Models.SverigesRadio.BaseModels;

namespace Sublime_Backend_Assessment.Controllers
{
    /// <summary>
    /// Handle All requests to SverigesRadioApi
    /// </summary>
    public class SverigesRadioController : Controller
    {
        #region Constructor

        private ISverigesRadioRepository _sverigesRadioRepository;

        public SverigesRadioController()
        {
            this._sverigesRadioRepository = new SverigesRadioRepository();
        }
        #endregion


        #region Api method call

        /// <summary>
        /// List all programs belonging to the category "Humor"
        /// </summary>
        public async Task<ActionResult> ProgramsByCategory()
        {
            var presenter = new List<ProgramGroupedPresenter>();
            var categories = await _sverigesRadioRepository.FetchCategoriesAsync();

            if (categories != null && categories.Count > 0)
            {
                int categoryId = categories.FirstOrDefault(ff => ff.Name.ToLower() == "humor").Id;
                string filter = "size=100&programcategoryid=" + categoryId;
                var programsWapper = await _sverigesRadioRepository.FetchProgramsAsync(filter);
                presenter = programsWapper.CastTo().ToList();
            }
            return View("Programme", presenter);
        }

        /// <summary>
        /// List only programs that have podcasts
        /// </summary>
        public async Task<ActionResult> ProgramsPodcasts()
        {
            string filter = "size=50&filter=program.haspod&filterValue=true";
            var programsWapper = await _sverigesRadioRepository.FetchProgramsAsync(filter,true);
            var presenter = programsWapper.CastTo().ToList();
            return View("Programme", presenter);
        }

        /// <summary>
        /// List only programs that are not archived
        /// </summary>
        public async Task<ActionResult> ProgramsNotArchived()
        {
            string filter = "size=100&filter=program.haspod&filterValue=true";
            var programsWapper = await _sverigesRadioRepository.FetchProgramsAsync(filter);
            var presenter = programsWapper.CastTo().ToList();
            return View("Programme", presenter);
        }
        #endregion       
    }
}

Sublime-Backend-Assessment/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Sveriges Radio";
}

<div class="jumbotron">
    <h1>Sveriges Radio</h1>
    <p class="lead"></p>
    <p>
        <ul>
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("Humor", "ProgramsByCategory", "SverigesRadio")</li>
            <li>@Html.ActionLink("Podcast", "ProgramsPodcasts", "SverigesRadio")</li>
            <li>@Html.ActionLink("Not Archived", "ProgramsNotArchived", "SverigesRadio")</li>
        </ul>
</div>

Sublime-Backend-Assessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sveriges Radio ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
    dd {
        border-bottom: 1px solid #44444414;
    }

    .card {
        box-shadow: 0 0 1px 1px #0001a;
    }

    .card-body {
        padding: 4px 8px;
    }

    .body-content {
        margin-top: 5px;
    }

    .d-flex {
        display: flex;
        justify-content: flex-start;
        align-items: flex-start;
    }

    .flex-row {
        flex-direction: row;
        flex-wrap: wrap;
    }

    .mb-3 {
        margin-bottom: 3em;
    }

    .mr-1 {
        margin-right: 1em;
    }

    a {
        text-decoration: none;
        color: #000000;
    }
</style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Humor", "ProgramsByCategory", "SverigesRadio")</li>
                    <li>@Html.ActionLink("Podcast", "ProgramsPodcasts", "SverigesRadio")</li>
                    <li>@Html.ActionLink("Not Archived", "ProgramsNotArchived", "SverigesRadio")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Sublime-Backend-Assessment/Views/SverigesRadio/PodcastPartial.cshtml
@model IEnumerable<Sublime_Backend_Assessment.Models.SverigesRadio.BaseModels.Podcast>

@{
    Layout = null;
}
<div class="d-flex flex-row mb-3">
    @foreach (var item in Model)
    {
        <div class="card mb-3 mr-1" style="width:16em">
            <div class="card-body">
                <h5 class="card-title">
                    @Html.DisplayFor(modelItem => item.Title)
                </h5>
                <blockquote class="blockquote mb-0">
                    <p>
                        @Html.DisplayFor(modelItem => item.Publishdateutc)
                    </p>
                    <footer class="blockquote-footer">
                        @Html.DisplayFor(modelItem => item.Duration)
                    </footer>
                </blockquote>
                <p class="card-text">
                    <audio controls style="width: 100%;">
                        <source src="@Html.DisplayFor(modelItem => item.Url)" type="audio/mpeg">
                        Your browser does not support the audio element.
                    </audio>
                </p>
            </div>
        </div>
    }
</div>

Sublime-Backend-Assessment/Views/SverigesRadio/Programme.cshtml
@model IEnumerable<Sublime_Backend_Assessment.Models.SverigesRadio.ProgramGroupedPresenter>

<dl>
    @foreach (var item in Model)
    {
        <dt>
            <h3>Category: <b>@Html.DisplayFor(modelItem => item.Name)</b> -- @(item.Programs.Count)</h3>
        </dt>

        <dd>
            <div class="d-flex flex-row mb-3">
                @foreach (var program in item.Programs)
                {
                    <div class="d-flex flex-row mb-3">
                        <a href="@(program.Programurl)">
                            <div class="card mb-3 mr-1" style="width: 20em;">
                                <img class="card-img-top" style="width:20em;"
                                     src="@Html.DisplayFor(modelItem => program.Programimage)"
                                     alt="@Html.DisplayFor(modelItem => program.Name)">
                                <div class="card-body">
                                    <h4 class="card-title">
                                        @Html.DisplayFor(modelItem => program.Name)
                                    </h4>
                                    <p class="card-text">
                                        @Html.DisplayFor(modelItem => program.Description)
                                    </p>
                                </div>
                            </div>
                        </a>
                        @if (program.Haspod && program.Podcasts != null)
                        {
                            Html.RenderPartial("PodcastPartial", program.Podcasts);
                        }
                    </div>
                }
            </div>
        </dd>
    }
</dl>